//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eczam_ADO_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disc()
        {
            this.Checkk = new HashSet<Checkk>();
        }
    
        public int Id { get; set; }
        public string Pichuri { get; set; }
        public string DiskName { get; set; }
        public string ColectiveName { get; set; }
        public string IzdatelName { get; set; }
        public int ColTrec { get; set; }
        public string Genre { get; set; }
        public System.DateTime YearPublishing { get; set; }
        public decimal Cost_price { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkk> Checkk { get; set; }
    }
}
